/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns 200 when the server is ready to accept traffic.
         */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export all trips, stops, and tags as a flat table
         * @description Returns one row per stop across all trips, with trip fields repeated per stop.
         *     Trips with no stops yield one row with empty stop fields.
         *     Responds with JSON (default) or CSV depending on the Accept header or ?format param.
         */
        get: operations["GetExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags, optionally filtered by name prefix
         * @description Returns tags whose slug starts with the normalized q parameter. Pass no q to return all tags. Useful for autocomplete.
         */
        get: operations["ListTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The slug of the tag to update. */
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a tag's display name
         * @description Updates only the display name of a tag. The slug is the stable identifier and is never changed by this operation.
         */
        patch: operations["PatchTag"];
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all trips */
        get: operations["ListTrips"];
        put?: never;
        /** Create a trip */
        post: operations["CreateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a trip by ID */
        get: operations["GetTrip"];
        /** Update a trip */
        put: operations["UpdateTrip"];
        post?: never;
        /** Delete a trip */
        delete: operations["DeleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        /** List all stops for a trip */
        get: operations["ListStops"];
        put?: never;
        /** Create a stop on a trip */
        post: operations["CreateStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/stops/{stopId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        /** Get a stop by ID */
        get: operations["GetStop"];
        /** Update a stop */
        put: operations["UpdateStop"];
        post?: never;
        /** Delete a stop */
        delete: operations["DeleteStop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/stops/{stopId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        /** List tags on a stop */
        get: operations["ListTagsByStop"];
        put?: never;
        /** Add a tag to a stop */
        post: operations["AddTagToStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/stops/{stopId}/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a tag from a stop */
        delete: operations["RemoveTagFromStop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        CreateTripRequest: {
            /** @example Summer Tour 2025 */
            name: string;
            /**
             * Format: date
             * @example 2025-06-01
             */
            start_date: string;
            /**
             * Format: date
             * @example 2025-06-15
             */
            end_date?: string | null;
            /** @example Pacific coast route */
            notes?: string;
        };
        Trip: {
            /**
             * Format: uuid
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /** @example Summer Tour 2025 */
            name: string;
            /**
             * Format: date
             * @example 2025-06-01
             */
            start_date: string;
            /**
             * Format: date
             * @example 2025-06-15
             */
            end_date?: string | null;
            /** @example Pacific coast route */
            notes?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorDetail: {
            /**
             * @description Machine-readable error code for client branching.
             * @example not_found
             */
            code: string;
            /**
             * @description Human-readable description of the error.
             * @example trip not found
             */
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        CreateStopRequest: {
            /** @example Yellowstone Camp */
            name: string;
            /** @example Yellowstone, WY */
            location?: string | null;
            /**
             * Format: date-time
             * @example 2025-06-02T10:00:00Z
             */
            arrived_at: string;
            /**
             * Format: date-time
             * @example 2025-06-04T09:00:00Z
             */
            departed_at?: string | null;
            /** @example Great views */
            notes?: string | null;
        };
        UpdateStopRequest: {
            /** @example Yellowstone Camp */
            name: string;
            /** @example Yellowstone, WY */
            location?: string | null;
            /**
             * Format: date-time
             * @example 2025-06-02T10:00:00Z
             */
            arrived_at: string;
            /**
             * Format: date-time
             * @example 2025-06-04T09:00:00Z
             */
            departed_at?: string | null;
            /** @example Great views */
            notes?: string | null;
        };
        Stop: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            trip_id: string;
            /** @example Yellowstone Camp */
            name: string;
            /** @example Yellowstone, WY */
            location?: string | null;
            /**
             * Format: date-time
             * @example 2025-06-02T10:00:00Z
             */
            arrived_at: string;
            /**
             * Format: date-time
             * @example 2025-06-04T09:00:00Z
             */
            departed_at?: string | null;
            /** @example Great views */
            notes?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Tags linked to this stop, ordered by slug. */
            tags?: components["schemas"]["Tag"][];
        };
        UpdateTripRequest: {
            /** @example Summer Tour 2025 */
            name: string;
            /**
             * Format: date
             * @example 2025-06-01
             */
            start_date: string;
            /**
             * Format: date
             * @example 2025-06-15
             */
            end_date?: string | null;
            /** @example Pacific coast route */
            notes?: string;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            /** @example National Park */
            name: string;
            /** @example national-park */
            slug: string;
            /** Format: date-time */
            created_at: string;
        };
        AddTagRequest: {
            /** @example National Park */
            name: string;
        };
        PatchTagRequest: {
            /** @example National Park */
            name: string;
        };
        ExportRow: {
            /** Format: uuid */
            trip_id: string;
            /** @example Summer Tour 2025 */
            trip_name: string;
            /**
             * Format: date
             * @example 2025-06-01
             */
            trip_start_date: string;
            /**
             * Format: date
             * @example 2025-06-15
             */
            trip_end_date?: string | null;
            /** @example Yellowstone Camp */
            stop_name?: string;
            /** @example Yellowstone, WY */
            stop_location?: string | null;
            /** Format: date-time */
            arrived_at?: string | null;
            /** Format: date-time */
            departed_at?: string | null;
            stop_notes?: string | null;
            /**
             * @example [
             *       "camping",
             *       "national-park"
             *     ]
             */
            tags: string[];
        };
        /** @description Pagination metadata returned with every list response. */
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /**
             * @description Total number of items matching the query (across all pages).
             * @example 45
             */
            total: number;
        };
        TripList: {
            data: components["schemas"]["Trip"][];
            pagination: components["schemas"]["Pagination"];
        };
        StopList: {
            data: components["schemas"]["Stop"][];
            pagination: components["schemas"]["Pagination"];
        };
        TagList: {
            data: components["schemas"]["Tag"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetExport: {
        parameters: {
            query?: {
                /** @description Response format. Overrides the Accept header when provided. */
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export data — one row per stop. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRow"][];
                    "text/csv": string;
                };
            };
        };
    };
    ListTags: {
        parameters: {
            query?: {
                /** @description Filter by slug prefix (case-insensitive). */
                q?: string;
                /** @description Page number (1-indexed). */
                page?: number;
                /** @description Number of items per page (max 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of matching tags ordered by slug. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    PatchTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The slug of the tag to update. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTagRequest"];
            };
        };
        responses: {
            /** @description Tag updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Tag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error — name is required. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListTrips: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed). */
                page?: number;
                /** @description Number of items per page (max 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of trips ordered by start_date descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripList"];
                };
            };
        };
    };
    CreateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Trip created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Validation error — missing required field or invalid date range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested trip. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description The updated trip. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted successfully. No response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListStops: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed). */
                page?: number;
                /** @description Number of items per page (max 100). */
                limit?: number;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of stops ordered by arrived_at ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopList"];
                };
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStopRequest"];
            };
        };
        responses: {
            /** @description Stop created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"];
                };
            };
            /** @description Trip not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested stop. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"];
                };
            };
            /** @description Stop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdateStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStopRequest"];
            };
        };
        responses: {
            /** @description The updated stop. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"];
                };
            };
            /** @description Stop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop deleted successfully. No response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListTagsByStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags linked to the stop, ordered by slug. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Stop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AddTagToStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagRequest"];
            };
        };
        responses: {
            /** @description Tag linked to the stop. Returns the tag. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Stop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error — tag name is required or contains no usable characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RemoveTagFromStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                stopId: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag removed from stop. No response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tag not linked to stop. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
